- name: configure {{ name }}
  ini_file:
    dest: "{{ ini_dest }}"
    section: "program:{{ name }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ configs }}"

- name: ensure present {{ name }} program
  supervisorctl:
    name: "{{ name }}"
    state: present
